package com.hotfix.rest.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

import com.hotfix.common.responses.domainobject.ResponseEntity;
import com.hotfix.jpa.data.repository.UserRepository;
import com.hotfix.jpa.enitity.User;

@RestController   // This means that this class is a RestController
public class UserRestController {
	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private  UserRepository userRepository;
	
	@RequestMapping(value = "/adduser",method = RequestMethod.GET)
    public ResponseEntity createUser() {
	   	ResponseEntity responseEntity=new ResponseEntity();
	   	try {
		   		User n = new User();
				n.setFirstName("dhiraj");
				n.setLastName("Singh");
				userRepository.save(n);
				responseEntity.setStatus("200");
	     	    return responseEntity;
	   	}catch(Exception ex){
	   		    responseEntity.setStatus("500");
	         	return responseEntity;
	   	}
   
   }
}
